import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";

export const metadata = {
  title: "Apollo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>{ children }</ApolloWrapper>
      </body>
    </html>
  );
}
